name = "angelfallz"
main = "workers-site/index.js"
compatibility_date = "2025-11-07"

[[kv_namespaces]]
binding = "SETTINGS"
id = "a48e1a0028fe455fa4862e223ba1a0f3"
preview_id = "a48e1a0028fe455fa4862e223ba1a0f3"

[site]
bucket = "./dist"

